language: perl
perl:
  - "5.18"
  - "5.20"
matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1
  allow_failures:
    - perl: "blead"
sudo: required
services:
- docker
script:
  - ci-tests/run-travis-main.sh    # parallel testing
  - ci-tests/slurm/travis-setup.sh # slurm testing
