matrix:
  include:
    - os: linux
      language: c
      sudo: required
      services:
        - docker
      script: ci-tests/slurm/travis-setup.sh; ci-tests/slurm/travis-run.sh # slurm testing
    - os: osx
      script: ci-tests/run-travis-main.sh #osx testing 
