---
abstract: 'A complete rewrite of the HPC::Runner libraries to incorporate project creation, DAG inspection, and job execution.'
author:
  - 'Jillian Rowe <jillian.e.rowe@gmail.com>'
build_requires:
  Capture::Tiny: '0'
  File::Slurp: '0'
  FindBin: '0'
  Slurp: '0'
  Test::Class::Moose: '0'
  Test::Class::Moose::Load: '0'
  Test::Class::Moose::Runner: '0'
  Test::More: '0.96'
  Text::Diff: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.16, Dist::Zilla version 6.006, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HPC-Runner-Command
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
requires:
  Algorithm::Dependency: '0'
  Algorithm::Dependency::Source::HoA: '0'
  Cwd: '0'
  DBM::Deep: '0'
  Data::Dumper: '0'
  DateTime: '0'
  DateTime::Format::Duration: '0'
  File::Basename: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::File: '0'
  IO::Select: '0'
  IPC::Cmd: '0'
  IPC::Open3: '0'
  JSON: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  Log::Log4perl: '0'
  MCE: '0'
  MCE::Queue: '0'
  Moose: '0'
  Moose::Role: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::App: '0'
  MooseX::App::Command: '0'
  MooseX::App::Role: '0'
  MooseX::App::Role::Log4perl: '0'
  MooseX::Object::Pluggable: '0'
  MooseX::Types::Path::Tiny: '0'
  Storable: '0'
  Symbol: '0'
  Template: '0'
  YAML::XS: '0'
  perl: '5.008005'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/jerowe/HPC-Runner-App/issues
  homepage: https://github.com/jerowe/HPC-Runner-App
  repository: https://github.com/jerowe/HPC-Runner-App.git
version: '0.01'
x_serialization_backend: 'YAML::Tiny version 1.69'
